### ISSUE TITLE
server side rendering example cannot support duplex micro fe node

### ISSUE THREAD

**Issue by xiabin1235910** [xiabin1235910/module-federation-examples#5]

**Comment by xiabin1235910** [comment]
website1 ---> website2 (remote) ---> storybook (remote)。

so website2 (remote) as the duplex micro fe node, but looks like loadable component cannot support that. 

The error comes out from website1

```
 bixia@LM-SHC-15009688  ~/git_repository/module-federation-examples/server-side-rendering/website1   main ±  http://localhost:3002/server/container.js
undefined:1040
/******/ 		var chunkLoadingGlobal = self["__LOADABLE_LOADED_CHUNKS__"] = self["__LOADABLE_LOADED_CHUNKS__"] || [];
         		                         ^

ReferenceError: self is not defined
    at eval (eval at <anonymous> (eval at <anonymous> (/Users/bixia/git_repository/module-federation-examples/server-side-rendering/website1/buildServer/main.js:34537:32)), <anonymous>:1040:37)
    at eval (eval at <anonymous> (eval at <anonymous> (/Users/bixia/git_repository/module-federation-examples/server-side-rendering/website1/buildServer/main.js:34537:32)), <anonymous>:1043:13)
    at eval (eval at <anonymous> (eval at <anonymous> (/Users/bixia/git_repository/module-federation-examples/server-side-rendering/website1/buildServer/main.js:34537:32)), <anonymous>:1053:12)
```
